# Generated by Django 4.2.19 on 2025-04-19 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_room_description_room_image_url_alter_room_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='image_url',
        ),
    ]
