# Generated by Django 4.2.19 on 2025-04-20 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_room_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/'),
        ),
        migrations.AddField(
            model_name='room',
            name='location',
            field=models.CharField(default='ห้องประชุมชั้น 1', max_length=200),
            preserve_default=False,
        ),
    ]
